### ISSUE TITLE
Container not starting 

### ISSUE THREAD

**Issue by Fernien** [Programmierus/ldap-mailcow#29]
Hey there,

i was wondering if this Project is still working and compatible with the newest mailcow version 2022-12b.
After adding the whole config i get the following error:

```
mailcowcustomized_ldap-mailcow  | 09.01.23 13:22:18 Config file conf/dovecot/ldap/passdb.conf unchanged
mailcowcustomized_ldap-mailcow  | 09.01.23 13:22:18 Config file conf/dovecot/extra.conf unchanged
mailcowcustomized_ldap-mailcow  | 09.01.23 13:22:18 Config file conf/sogo/plist_ldap unchanged
mailcowcustomized_ldap-mailcow  | Traceback (most recent call last):
mailcowcustomized_ldap-mailcow  |   File "syncer.py", line 181, in <module>
mailcowcustomized_ldap-mailcow  |     main()
mailcowcustomized_ldap-mailcow  |   File "syncer.py", line 31, in main
mailcowcustomized_ldap-mailcow  |     sync()
mailcowcustomized_ldap-mailcow  |   File "syncer.py", line 54, in sync
mailcowcustomized_ldap-mailcow  |     (api_user_exists, api_user_active, api_name) = api.check_user(email)
mailcowcustomized_ldap-mailcow  |   File "/api.py", line 57, in check_user
mailcowcustomized_ldap-mailcow  |     rsp = req.json()
mailcowcustomized_ldap-mailcow  |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
mailcowcustomized_ldap-mailcow  |     return complexjson.loads(self.text, **kwargs)
mailcowcustomized_ldap-mailcow  |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
mailcowcustomized_ldap-mailcow  |     return _default_decoder.decode(s)
mailcowcustomized_ldap-mailcow  |   File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
mailcowcustomized_ldap-mailcow  |     raise JSONDecodeError("Extra data", s, end)
mailcowcustomized_ldap-mailcow  | json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

Any ideas? Or is this project dead?

**Comment by ghost** [comment]
It's working but you have to modify and tweak it , you might have different settings and parameters
